### ISSUE TITLE
Без указания Amount при отмене api ругается на невалидный токен

### ISSUE THREAD

**Issue by ValGoldun** [nikita-vanyasin/tinkoff#2]
Привет! 
Есть вызов:
```go
req := &tinkoff.CancelRequest{
		PaymentID: payment.ID,
}
_, err = tinkoffClient.Cancel(req)
if err != nil {
	...
	return
}
```

При формировании токена Amount равен нулю и после конкатенации и вычисления хеша этот токен становится невалиден для api, видимо они вообще не хотят получать этот 0, судя по документации тинькофф вызов без Amount - вполне обычная ситуация, так как параметр необязателен, вот пример из их доки:
```json
{
 "TerminalKey" :" TinkoffBankTest",
 "PaymentId" : "2164657",
 "Token" : "328a1ed43e3800c142b298fbb01772c739c524dd455717c8a9152428037439fb"
}
```

**Comment by nikita-vanyasin** [comment]
Спасибо! Исправление доступно в версии v1.0.2
