### ISSUE TITLE
Проблема с QR

### ISSUE THREAD

**Issue by max107** [nikita-vanyasin/tinkoff#9]
Есть подозрение, что в 

```
func (i *GetQRRequest) GetValuesForToken() map[string]string {
	return map[string]string{
		"PaymentId":   i.PaymentID,
		"TerminalKey": i.TerminalKey,
	}
}
```

не хватает

```
"DataType":    i.DataType,
```

**Comment by nikita-vanyasin** [comment]
@max107 спасибо! Поправил, должно быть доступно в последней версии пакета: https://github.com/nikita-vanyasin/tinkoff/releases/tag/v1.2.1

@AlexTransit FYI^. Также обнаружил, что методы для тестирования СБП имеют неправильные сигнатуры и используют невалидный URL. В следующем PR поправлю.

**Comment by max107** [comment]
@nikita-vanyasin не уверен на счет сигнатур, так как СБП работает корректно, проблем не замечал. Правда есть ньюанс, я использую доработанный форк.

**Comment by nikita-vanyasin** [comment]
@max107 там были SPB вместо SBP - в том числе в URL. Уже поправил в этом пакете.

**Comment by max107** [comment]
Кажется что то такое исправлял. Спасибо.

**Comment by max107** [comment]
Попробую найти время и принести вам МР с изменениями из своего форка. Вдруг сторгуемся ;)
